### PR TITLE
[fix] Close vulnerability by adding `rel="noopener"`

### PR DESCRIPTION
**Pull request by zooley**
External URLs with `target="_blank"` should have either `rel="noopener"`
or `rel="noreferrer" to prevent malicious use of `window.opener`..

Refs: https://developers.google.com/web/tools/lighthouse/audits/noopener

### CODE REVIEW

**Comment by MorganRodgers** [comment]
@ericfranz and @johrstrom this works for me; should we recommend to @zooley that they apply these changes to https://github.com/OSC/ondemand/tree/master/apps/dashboard so that they can get Git-credit for the changes?

**Comment by zooley** [comment]
I'm still pretty new to OOD. If I made the PR on the wrong repo, please let me know. I'm happy to re-submit where/how you want.

**Comment by MorganRodgers** [comment]
No worries @zooley this *was* the right repo until about a week ago. We're in-progress on moving from using individual repos for our core applications to a single mono-repo.

Yes, please apply your changes to https://github.com/OSC/ondemand/tree/master/apps/dashboard.

**Comment by zooley** [comment]
New PR made: https://github.com/OSC/ondemand/pull/88

Should I close this one?

**Comment by MorganRodgers** [comment]
Closing in favor of OSC/ondemand#88.

**Pull request closed without merging**
