### PR TITLE
Simplify dashboard log out to use new Apache /logout URL

### PR DESCRIPTION
**Pull request by ericfranz**
After https://github.com/OSC/ood-portal-generator/issues/6 was implemented, we can now move the responsibility for deciding how to logout to Apache.

This also addresses https://github.com/OSC/ood-dashboard/issues/123

The solution:

1. logout URL is now just "/logout"
2. Apache by default is configured to redirect to /pun/sys/dashboard/logout so this route is added to tell the user to close the browser and possibly clear cookies:

screen shot 2017-02-23 at 8 44 13 am
screen shot 2017-02-23 at 8 44 16 am

### CODE REVIEW

**Comment by ericfranz** [comment]
I need to do 2 things:

1. rebuild this on a web dev node to avoid the annoying lines added to the Gemfile

    > BUNDLED WITH
    > 1.14.4

2. Test and verify that /logout when running the dashboard at /pun/sys/dashboard is actually to /logout and not to /pun/sys/dashboard/logout for both the dropdown and non dropdown versions

**Comment by ericfranz** [comment]
Experiment with using label to show "Logged in as $USERNAME". Not sure:

screen shot 2017-02-24 at 3 55 40 pm

screen shot 2017-02-24 at 3 55 38 pm

**Comment by ericfranz** [comment]
Going to revert for now. Option for later.

screen shot 2017-02-24 at 3 59 07 pm
screen shot 2017-02-24 at 3 59 08 pm

**Comment by ericfranz** [comment]
screen shot 2017-02-24 at 4 06 39 pm
screen shot 2017-02-24 at 4 06 42 pm
screen shot 2017-02-24 at 4 06 47 pm

**Comment by ericfranz** [comment]
@basilgohar do you have any objection to these changes? If not, I'll go with it. If, lets discuss offline next week.

1. moved "Change HPC Password" to the Help dropdown
2. changed "Logged in as $USERNAME" to plain text
3. Added a Log Out button that will always appear now

This is because of the recent infrastructure changes Jeremy pushed which included adding a /logout to Apache. So now the admin setting up authentication can also setup logout in one place and the dashboard installation is simpler. Also, with basic auth, /logout for Apache will redirect to /pun/sys/dashboard/logout which will instruct the user to close her browser and possibly delete cookies.

**Comment by basilgohar** [comment]
@ericfranz Sounds fine to me.  Thanks.

**Pull request merged**
